# adapted from https://github.com/andyli/HaxeCI/blob/master/.travis.yml
language: haxe

env:
    matrix:
    - TARGET=interp

# Test with Current Haxe and Haxe development.
haxe:
  - "3.4.2"
  - development

matrix:
  # Allow Haxe development to fail.
  allow_failures:
    - haxe: development

install:
  # install haxelibs
  - haxelib install buddy

script:
  - haxe test.${TARGET}.hxml

branches:
      only:
          - master